services: docker

env:
  global:
    - HOSTNAME: vccw.dev
      MACHINE_NAME: vccw
      VM_DIR: /vagrant

before_install:
  - docker pull ubuntu:16.04
  - tmpfile=$(mktemp)
  - docker run --detach --add-host "${HOSTNAME}$(echo -e "\t")${MACHINE_NAME}":127.0.0.1 --volume="${PWD}":${VM_DIR}/:rw --privileged ubuntu:16.04 "/sbin/init" > "${tmpfile}"
  - CONTAINER_ID=$(cat ${tmpfile})
  - docker exec --tty ${CONTAINER_ID} bash ${VM_DIR}/bin/setup-docker.sh

script:
  - docker exec --tty ${CONTAINER_ID} env TERM=xterm ansible-playbook middleware.yaml -i hosts --connection=local
  - docker exec --tty ${CONTAINER_ID} env TERM=xterm ansible-playbook ${VM_DIR}/provision/playbook.yml -i hosts -e "@test.json" --connection=local
  - ls -al
