services: docker

env:
  global:
    - HOSTNAME: vccw.dev
      MACHINE_NAME: vccw
      VM_DIR: /vagrant

before_install:
  - docker pull ubuntu
  - tmpfile=$(mktemp)
  - docker run --detach --add-host "${HOSTNAME}$(echo -e "\t")${MACHINE_NAME}":127.0.0.1 --volume="${PWD}":${VM_DIR}/:rw --privileged ubuntu:16.04 "/sbin/init" > "${tmpfile}"
  - CONTAINER_ID=$(cat ${tmpfile})
  - echo "[default]" > hosts
  - echo "localhost" >> hosts
  - ruby -ryaml -rjson -e "conf = {:vccw =>YAML.load(STDIN.read)}; conf[:vccw][:vagrant_dir] = \"${VM_DIR}\"; puts JSON.generate(conf);" < provision/default.yml > test.json
  - curl https://raw.githubusercontent.com/vccw-team/vccw-xenial64/master/provision/playbook.yml > middleware.yaml
  - docker exec --tty ${CONTAINER_ID} sudo apt-get install software-properties-common
  - docker exec --tty ${CONTAINER_ID} sudo apt-add-repository ppa:ansible/ansible
  - docker exec --tty ${CONTAINER_ID} sudo apt-get update
  - docker exec --tty ${CONTAINER_ID} sudo apt-get install ansible

script:
  - docker exec --tty ${CONTAINER_ID} env TERM=xterm ansible-playbook ${VM_DIR}/middleware.yaml -i ${VM_DIR}/hosts --connection=local
  - docker exec --tty ${CONTAINER_ID} env TERM=xterm ansible-playbook ${VM_DIR}/provision/playbook.yml -i ${VM_DIR}/hosts -e "@${VM_DIR}/test.json" --connection=local
  - ls -al
