services: docker

env:
  global:
    - HOSTNAME: vccw.dev
      MACHINE_NAME: vccw
      VM_DIR: /vagrant

before_install:
  - docker pull ubuntu:16.04
  - tmpfile=$(mktemp)
  - docker run --detach --add-host "${HOSTNAME}$(echo -e "\t")${MACHINE_NAME}":127.0.0.1 --volume="${PWD}":${VM_DIR}/:rw --privileged ubuntu:16.04 "/sbin/init" > "${tmpfile}"
  - CONTAINER_ID=$(cat ${tmpfile})
  - docker exec --tty ${CONTAINER_ID} bash ${VM_DIR}/bin/setup-docker.sh

before_script:
  - docker exec --user ubuntu --tty ${CONTAINER_ID} env TERM=xterm ansible-playbook /home/ubuntu/middleware.yaml -i /home/ubuntu/hosts --connection=local
  - docker exec --user ubuntu --tty ${CONTAINER_ID} env TERM=xterm ansible-playbook ${VM_DIR}/provision/playbook.yml -i /home/ubuntu/hosts -e "@/home/ubuntu/test.json" --connection=local
  - docker exec --user ubuntu --tty ${CONTAINER_ID} env TERM=xterm bundle install
script:
  - docker exec --user ubuntu --tty ${CONTAINER_ID} env TERM=xterm bundle exec rake spec
