services: docker

env:
  global:
    - HOSTNAME: vccw.dev
      MACHINE_NAME: vccw
      IP: 192.168.33.10
      VM_DIR: /vagrant
      DISTRO: ubuntu1604

before_install:
  # Pull container.
  - docker pull geerlingguy/docker-${DISTRO}-ansible:latest
  - bundle install --path vendor/bundler
  - tmpfile=$(mktemp)
  - docker run --detach --add-host "${HOSTNAME}$(echo -e "\t")${MACHINE_NAME}":127.0.0.1 --volume="${PWD}":${VM_DIR}/:rw --privileged geerlingguy/docker-${DISTRO}-ansible:latest "/sbin/init" > "${tmpfile}"
  - CONTAINER_ID=$(cat ${tmpfile})
  - docker inspect $CONTAINER_ID
  - echo "[default]" > hosts
  - echo "localhost" >> hosts
  - ruby -ryaml -e "conf = {:vccw =>YAML.load(STDIN.read)}; conf[:vccw][:vagrant_dir] = \"${VM_DIR}\"; puts YAML.dump(conf);" < provision/default.yml > test.yml
  - cat test.yml

script:
  - docker exec --tty ${CONTAINER_ID} env TERM=xterm ansible-playbook ${VM_DIR}/provision/playbook.yml -i ${VM_DIR}/hosts -e "@${VM_DIR}/test.json"
  - ls -al
